'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("trienlamtranh.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _04A1D442_FCD1_4B1D_9738_9B6953B640FB_300x300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("04A1D442-FCD1-4B1D-9738-9B6953B640FB-300x300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6DE9D5E0_65AC_4DE5_B60F_9215B7F3BF04_300x199() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6DE9D5E0-65AC-4DE5-B60F-9215B7F3BF04-300x199", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CE1BE5AB_F729_4016_B0BC_A90BAC4FD329_300x199() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CE1BE5AB-F729-4016-B0BC-A90BAC4FD329-300x199", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cua_hang_khung_tranh_385_duong_ngoc_hoi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cua-hang-khung-tranh-385-duong-ngoc-hoi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FB_IMG_1649683608340_1_300x209() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FB_IMG_1649683608340-1-300x209", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20220411_202502_1_300x415() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20220411_202502-1-300x415", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20220411_202719_1_300x430() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20220411_202719-1-300x430", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_7017_300x213() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_7017-300x213", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_canvas4_300x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-canvas4-300x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_co_dien_hoa_tiet_vang_sieu_dep_300x200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-co-dien-hoa-tiet-vang-sieu-dep-300x200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_go_nhu_vang_sieu_dep_sang_trong_300x200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-go-nhu-vang-sieu-dep-sang-trong-300x200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_mau_nau_be_mat_phang_min_don_gian_va_dep_300x142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-mau-nau-be-mat-phang-min-don-gian-va-dep-300x142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_mau_nau_be_mat_phang_min_don_gian_va_dep_300x1421() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-mau-nau-be-mat-phang-min-don-gian-va-dep-300x1421", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_mau_nau_gu_hoa_tiet_nhan_be_mat_sieu_dep_300x142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-mau-nau-gu-hoa-tiet-nhan-be-mat-sieu-dep-300x142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property khung_tranh_vien_nau_den_hoa_tiet_vang_anh_kim_dep_va_sang_trong_1_300x248() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("khung-tranh-vien-nau-den-hoa-tiet-vang-anh-kim-dep-va-sang-trong-1-300x248", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qweqewqwqweqweqweqeqeqweqweqeqeqweqweqweqwe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qweqewqwqweqweqweqeqeqweqweqeqeqweqweqweqwe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ra_mat_trung_tam_trien_lam_nghe_thuat_dau_tien_trong_cac_truong_nghe_thuat_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ra-mat-trung-tam-trien-lam-nghe-thuat-dau-tien-trong-cac-truong-nghe-thuat-5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tải_xuống() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tải xuống", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
